import React, { useState } from 'react';

export const DataTrustModal: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => {
  const [message, setMessage] = useState('');
  const [restorePath, setRestorePath] = useState<string | null>(null);
  if (!isOpen) return null;
  const run = async (task: () => Promise<string | null>) => { try { const result = await task(); setMessage(result ? `Saved: ${result}` : 'Cancelled.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not complete that action.'); } };
  return <div className="modal-overlay" role="dialog" aria-modal="true" aria-label="Data and backups"><div className="modal-content" style={{ width: 470 }}><h2 style={{ marginTop: 0 }}>Your data stays yours</h2><p style={{ color: 'var(--text-secondary)' }}>Backups stay on this Mac. Exports never include AI credentials.</p><div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}><button className="btn-ghost" onClick={() => run(async () => window.beacon.data.createBackup())}>Create local backup</button><button className="btn-ghost" onClick={() => run(() => window.beacon.data.exportJson())}>Export all Beacon data (.json)</button><button className="btn-ghost" onClick={() => run(() => window.beacon.data.exportCsv('goals'))}>Export goals (.csv)</button><button className="btn-ghost" onClick={() => run(() => window.beacon.data.exportCsv('progress'))}>Export progress (.csv)</button><button className="btn-ghost" onClick={async () => { try { const preview = await window.beacon.data.previewImport(); setRestorePath(preview?.filePath ?? null); setMessage(preview ? `Ready to restore ${Object.values(preview.counts).reduce((sum, count) => sum + count, 0)} records. Beacon will create a safety backup first.` : 'Cancelled.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not inspect export.'); } }}>Preview a restore</button>{restorePath && <button className="btn-primary" onClick={async () => { await window.beacon.data.importJson(restorePath); setMessage('Restore completed. A pre-restore backup was created.'); setRestorePath(null); }}>Apply restored data</button>}</div>{message && <p style={{ marginTop: 14, color: 'var(--text-secondary)', fontSize: 12, wordBreak: 'break-word' }}>{message}</p>}<div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 18 }}><button className="btn-primary" onClick={onClose}>Done</button></div></div></div>;
};
